export default (categories = [
  "Common I",
  "Common II",
  "Common III",
  "Common IV",
  "Common V",
  "Common VI",
  "Basic I",
  "Basic II",
  "Basic III",
  "Basic IV",
  "Basic V",
  "Basic VI",
  "Basic VII",
  "Advanced I",
  "Advanced II",
  "Advanced III",
  "Advanced IV",
  "Advanced V",
  "Advanced VI",
  "Advanced VII"
]);
